#%RAML 1.0
title: BitCtrl CMS JSON API
version: v1
protocols: [ HTTPS ]
baseUri: https://bitctrl.de/dav/api/{version}
mediaType:  application/json

uses:
  types: types.raml

/systemobjekte:
  get:
    responses:
      200:
        body:
          type: types.SystemObjekt[]
  post:
    body:
      application/json:
        type: types.SystemObjekt []
/onlinedaten:
  post:
    body:
      application/json:
        type: types.OnlineDatum []
