#%RAML 1.0
title: BitCtrl CMS JSON API
version: v1
protocols: [ HTTPS ]
baseUri: https://bitctrl.de/dav/api/{version}
mediaType:  application/json

uses:
  types: types.raml

/systemobjekte:
  get:
    responses:
      200:
        body:
          type: types.SystemObjekt[]
  /messquerschnitte:
    post:
      body:
        application/json:
          type: types.MessQuerschnitt []
  /anzeigequerschnitt:
    post:
      body:
        application/json:
          type: types.AnzeigeQuerschnitt []
  /anzeige:
    post:
      body:
        application/json:
          type: types.Anzeige []
/onlinedaten:
  /messquerschnitt:
    /verkehrsdatenkurzzeit:
      post:
        body:
          application/json:
            type: types.VerkehrsdatenKurzzeit []
  /anzeige:
    /anzeigeeigenschaft:
      post:
        body:
          application/json:
            type: types.AnzeigeEigenschaft []
