#%RAML 1.0
title: BitCtrl CMS JSON API
version: v1
protocols: [ HTTPS ]
baseUri: https://bitctrl.com/bccms/api/{version}
mediaType:  application/json

uses:
  types: types.raml

/systemobjects:
  get:
    responses:
      200:
        body:
          type: types.SystemObject[]
  post:
    body:
      application/json:
        type: types.SystemObject []
/onlinedaten:
  post:
    body:
      application/json:
        type: types.OnlineDatum []
