#%RAML 1.0 Library

types:
  SystemObjekt:
    description: |
     Basistyp für statische Daten.
    type: object
    additionalProperties: false
    properties:
      id: string
      name: string
      version:
        description: |
         Der Zeitpunkt, der letzten Änderung der statischen Daten dieses Objekte.
        type: datetime
  PunktXY:
    description: |
     Georeferenziertes SystemObjekt (statische Daten). Die Koordinaten werden in WGS84 abgebildet. Für Niedersachsen sind die WGS Koordinaten geprüft und valide.
    type: SystemObjekt
    properties:
      breite: number
      laenge: number
  FahrstreifenLage:
    description: |
     die Lage des Fahrstreifens auf der Straße. (1ÜFS => 1.    Überholfahrstreifen)
    type: string
    enum:
      - HFS
      - 1ÜFS
      - 2ÜFS
      - 3ÜFS
      - 4ÜFS
      - 5ÜFS
      - 6ÜFS
  MessQuerschnitt:
    description: |
      Ein Messquerschnitt (statische Daten) ( <a href="https://www.nerz-ev.de/datkat/kb.tmVerkehrGlobal.html#typ.messQuerschnittAllgemein">typ.messQuerschnittAllgemein</>  ).
    type: PunktXY
    properties:
      fahrstreifen:
        description: Die Menge aller Fahrstreigen an diesem Messquerschnitt (Referenziert via id)
        type: string[]
  Anzeige:
    description: |
      Eine Anzeige (statische Daten) an einem Anzeigequerschnitt ( <a href="https://www.nerz-ev.de/datkat/kb.tmAnzeigenGlobal.html#typ.anzeige">typ.anzeige</>  ).
    type: SystemObjekt
    properties:
      fahrstreifen: FahrstreifenLage []
  FahrStreifen:
    description: |
      Ein Fahrstreifen (statische Daten) auf einem Messquerschnitt ( <a href="https://www.nerz-ev.de/datkat/kb.tmVerkehrGlobal.html#typ.fahrStreifen">typ.fahrStreifen</>  ).
    type: SystemObjekt
    properties:
      lage: FahrstreifenLage
  AnzeigeQuerschnitt:
    description: |
      Ein Anzeigequerschnitt (statische Daten) ( <a href="https://www.nerz-ev.de/datkat/kb.tmAnzeigenGlobal.html#typ.anzeigeQuerschnitt">typ.anzeigeQuerschnitt</>  ).
    type: PunktXY
    properties:
      anzeigen:
        description: Menge aller Anzeigen an diesem Anzeigequerschnitt (Referenziert via id)
        type: string[]
  OnlineDatum:
    description: |
     Basistyp für dynamische Daten.
    type: object
    additionalProperties: false
    properties:
      systemObjektId: string
      datenStatus: string
      zeitstempel: datetime
  Verkehrsstaerke:
    description: Anzahl der Fahrzeuge pro Intervall.
    type: object
    additionalProperties: false
    properties:
      wert: integer
      guete: number
      dimension:
        type: string
        description: Die Dimension für die Verkehrsstärke. Normalersweise "Fz/h" oder "Fz/Intervall". Bei ungültigen Daten "".
  Geschwindigkeit:
    description: Geschwindigkeit (von Fahrzeugen) in km/h.
    type: object
    additionalProperties: false
    properties:
      wert: integer
      guete: number
  VerkehrsdatenKurzzeit:
    description: |
      Verkehrsdaten ( dynamische Kurzzeitdaten) mit Intervallwerten (teilweise normiert auf Stundenwerte) für Messquerschnitte und Fahrstreifen ( <a  href="https://www.nerz-ev.de/datkat/kb.tmVerkehrGlobal.html#atg.verkehrsDatenKurzZeitMq">atg.verkehrsDatenKurzZeitMq</> & <a href="https://www.nerz-ev.de/datkat/kb.tmVerkehrGlobal.html#atg.verkehrsDatenKurzZeitFs">atg.verkehrsDatenKurzZeitFs</> & <a href="https://www.nerz-ev.de/datkat/kb.tmVerkehrGlobal.html#atg.verkehrsDatenKurzZeitIntervall">atg.verkehrsDatenKurzZeitIntervall</> ).
      Der Zeitstempel ist vom Anfang des Intervalls.
    type: OnlineDatum
    properties:
      aspekt:
        description: Die Variante der Kurzzeitdaten.
        type: string
        enum:
          - Analyse
          - Aggregation1Minute
          - Aggregation5Minuten
          - Aggregation15Minuten
          - Aggregation30Minuten
          - Aggregation60Minuten
          - AnalyseHB
          - ExterneErfassung
          - MesswertErsetzung
          - PlausibilitätsprüfungFormal
          - PlausibilitätsprüfungLogisch
      qKfz: Verkehrsstaerke
      vKfz: Geschwindigkeit
      qLkw: Verkehrsstaerke
      vLkw: Geschwindigkeit
      qPkw: Verkehrsstaerke
      vPkw: Geschwindigkeit
      b:
        displayName: Belegungsgrad in Prozent 0-100%
        type: number
  AnzeigeQuerschnittEigenschaft:
    description: |
      OnlineDatum eines Anzeigequerschnitts (dynamische Daten) ( <a href="https://www.nerz-ev.de/datkat/kb.tmAnzeigenGlobal.html#atg.anzeigeQuerschnittEigenschaftIst">	atg.anzeigeQuerschnittEigenschaftIst</> )
    type: OnlineDatum
    properties:
      status:
        description: Der Status der Anzeige.
        type: string
        enum:
          - Undefiniert
          - OK
          - Gestört
          - Teilstörung
          - Stromausfall
          - Kommunikationsausfall
          - Türkontakt
      helligkeit:
        description: |
          Die Helligkeit der Anzeige des Anzeigequerschnittes in %.
        type: number
      betriebszustand:
        description: Betriebsart, mit der der Anzeigequerschnitt betrieben wird.
        type: string
        enum:
          - Undefiniert
          - Normalbetrieb
          - Blindbetrieb
          - Vorortbetrieb
          - Autarkbetrieb
          - Testbetrieb
          - Notbetrieb
          - ExterneSteuerung
          - Tunnelbetrieb
  AnzeigeQuerschnittHelligkeitsMeldung:
    description: |
      Die am Anzeigequerschnitt gemessene Umgebungshelligkeit.
    type: OnlineDatum
    properties:
      helligkeit:
        description: |
          Die Helligkeit in Lux.
        type: number
  AnzeigeEigenschaft:
    description: |
        OnlineDatum einer Anzeige (dynamische Daten) ( <a href=https://www.nerz-ev.de/datkat/kb.tmAnzeigenGlobal.html#atg.anzeigeEigenschaftIst">atg.anzeigeEigenschaftIst</> ).
    type: OnlineDatum
    properties:
      status:
        description: Der Status der Anzeige.
        type: string
        enum:
          - Undefiniert
          - OK
          - Gestört
          - Teilstörung
          - Stromausfall
          - Kommunikationsausfall
          - Türkontakt
      wvzInhalt:
        description: Grafischer Anzeigeinhalt, textuell abgebildet.
        type: string
        required: false
      text:
        description: Der Freitext, wenn die Anzeige Texte darstellen kann.
        type: string
        required: false
      grafik:
        description: |
          Die angezeigte Grafik (optional) als Base64 codierter String.
        type: string
        required: false
  Glaettemeldeanlage:
      description: |
       Beschreibung einer Glättemeldeanlage (statische Daten) zur Abbildung der logischen Struktur eines SWIS Netzwerkes. Dieser Typ ist Anlagenspezifisch und kein Standard ERZ Typ.
      type: PunktXY
      properties:
        dwdKennung: string
        höhe:
          description: |
            Die Höhe der Anlage über dem Meerespiegel in Metern.
          type: integer
  GmaUmfelddaten:
    description: |
     Umfelddaten einer Glättemeldeanlage (dynamische Daten), zusammengefasst für maßgebliche Sensoren. Der Zeitstempel ist der Messzeitpunkt.
    type: OnlineDatum
    properties:
      atmosphärendaten: Atmosphaerendaten
      umfeldatenFürFahrstreifen: UmfelddatenFuerFahrstreifen[]
  Atmosphaerendaten:
    description: |
     Umfelddaten an einer GMA, die keinem Fahrstreifen zugeordnet werden.
    type: object
    additionalProperties: false
    properties:
      luftTemperatur:
        description: |
         Die Lufttemperatur in °C.
        type: number
        maximum: 100
        minimum: -100
      niederschlagsIntensität:
        description: |
         Die Niederschlagsintensität in mm/h.
        type: number
        maximum: 20
        minimum: 0
      luftDruck:
        description: |
         Der Luftdruck in hPa.
        type: number
        maximum: 2000
        minimum: 0
      relativeLuftfeuchte:
        description: |
         Relative Luftfeuchte der in Nähe der Fahrbahnmessstelle befindlichen Umgebungsluft in %.
        type: number
        maximum: 100
        minimum: 0
      windRichtung:
        description: |
         Richtung aus der der Wind weht in Grad (°). Die Windrichtung wird als vektorieller Mittelwert (Windrichtung und - geschwindigkeit) über ein gleitendes Zeitintervall von 10 Minuten ermittelt.
        type: number
        maximum: 359
        minimum: 0
      windGeschwindigkeitMittelWert:
        description: |
         Geschwindigkeit des Windes in horizontaler Ebene (Komponente) in Meter pro Sekunde (m/s). Windgeschwindigkeit (Mittel) wird als vektorieller Mittelwert über ein gleitendes Zeitintervall von 10 Minuten ermittelt.
        type: number
        maximum: 1000
        minimum: 0
      schneeHöhe:
        description: |
         Gibt die Höhe der Schneebedeckung in cm an einer definierten Messstelle in Bezug zu einer ebenen, senkrechten Fläche an. 0 cm wird gemeldet, wenn die ebene senkrechte Fläche völlig unbedeckt ist. Die Schneeoberfläche sollte durch die Messung nicht beeinflusst werden. Die Schneehöhe hat nichts mit der Bedeckung der Straßenoberfläche von Fahrspuren zu tun.
        type: number
        maximum: 500
        minimum: 0
      sichtWeite:
        description: |
         Sichtweite bezogen auf eine Kontrastschwelle von 5% an der Messstelle in Meter.
        type: number
        maximum: 2000
        minimum: 10
      helligkeit:
        description: |
         Helligkeit ist definiert als Beleuchtungsstärke (Anteil des auf eine ebene Messfläche senkrecht auftreffenden Komponente des Lichtstroms im sichtbaren Spektralbereich) in Lux angegeben.
        type: number
        maximum: 60000
        minimum: 0
      windGeschwindigkeitSpitzenWert:
        description: |
         Geschwindigkeit des Windes in horizontaler Ebene (Komponente) in Meter pro Sekunde (m/s). Windgeschwindigkeit (Spitze) ist die maximale Windgeschwindigkeit der letzten 10 Minuten.
        type: number
        maximum: 100
        minimum: 0
      taupunktTemperatur:
        description: |
         Taupunkttemperatur ist diejenige Temperatur, bei der die in der Umgebungsluft der Messstelle (am Ort der Temperatur und Feuchte-Sensorik) befindliche Feuchte zu kondensieren beginnt in °C.
        type: number
        maximum: 100
        minimum: -100
      niederschlagsArt:
        description: |
         In der Atmosphäre fallender Niederschlag.
        type: string
      niederschlagsMenge:
        description: |
         Die Intensität wird in Bezug auf Niederschlag in flüssiger Form durch Volumen (1 l/m2 = 1 mm) pro Zeiteinheit (mm/h) angegeben.
        type: number
        maximum: 200
        minimum: 0
  UmfelddatenFuerFahrstreifen:
    description: |
     Umfelddaten einer GMA, die genau einem Fahrstreifen zugeordnet sind.
    type: object
    additionalProperties: false
    properties:
       fahrBahnOberflächenTemperatur:
         description: |
          Die Fahrbahnoberflächentemperatur wird in Grad Celsius (°C) angegeben.
         type: number
         maximum: 100
         minimum: -100
       restsalz:
         description: |
          Sättigungsgrad des gelösten Salzes auf der Fahrbahn (bzw. auf der Fahrbahnsensorik). SR wird in Prozent (%) angegeben.
         type: number
         maximum: 100
         minimum: 0
       gefrierTemperatur:
         description: |
          Die Gefriertemperatur ist diejenige Temperatur in Grad Celsius (°C), bei der die an der Oberfläche der Sonde vorhandene wässrige Taumittel-Lösung gefrieren (Übergang in den festen Aggregatszustand) könnte.
         type: number
         maximum: 100
         minimum: -100
       temperaturInTiefe1:
         description: |
          Temperatur in °C
         type: number
         maximum: 100
         minimum: -100
       temperaturInTiefe2:
         description: |
          Temperatur in °C
         type: number
         maximum: 100
         minimum: -100
       temperaturInTiefe3:
         description: |
          Temperatur in °C
         type: number
         maximum: 100
         minimum: -100
       fahrBahnOberFlächenZustand:
         description: |
          Der Zustand der Fahrbahnoberfläche.
         type: string
         enum:
           - trocken
           - feucht
           - nass
           - gefrorenes Wasser
           - Schnee/Schneematsch
           - Eis
           - Raureif
       wasserFilmDicke:
         description: |
          Bei wasserfildicken (WFD) oberhalb 0,1 mm wird nur eine Messgenauigkeit im 1/10 mm Bereich erreicht. Bei WFD oberhalb 2 mm liegt die Messgenauigkeit in der Regel im mm Bereich. Die rechnerische Wasserfilmdicke gibt die Fahrbahnbenetzung in mm (= Liter/m2 ) mit Wasser oder wässriger Lösung (Salzgemisch) an, welche sich am Messort bzw. auf der in der Fahrbahn eingelassenen Sonde befindet. Die Wasserfilmdicke ist immer bezogen auf eine glatte ebene Fläche.
         type: number
         maximum: 200
         minimum: 0
       tauStoffKonzentration:
         description: |
           Prozentualer Anteil des gelösten Taustoffs im Wasser auf der Fahrbahn (bzw. auf der Fahrbahnsensorik).
         type: number
       fahrBahnGlätte:
         description: |
          Ergebnisse der Glättewarnung und Prognose.
         type: string
         enum:
           - keine Glättegefahr
           - Eisglätte möglich
           - Tendenzberechnung nicht möglich
           - Schneeglätte oder Glatteis bei Niederschlag möglich
           - Schneeglätte oder Glatteis bei Niederschlag sofort möglich
           - Eisglätte sofort möglich
           - Glätte vorhanden
           - Eis oder Schnee auf der Fahrbahn
       zeitreserveEisglätte:
         description: |
           Gibt die Zeit bis zu einer möglichen Eisglätte in Minuten an.
         type: integer
       zeitreserveReifglätte:
         description: |
           Gibt die Zeit bis zu einer möglichen Reifglätte in Minuten an.
         type: integer
