#%RAML 1.0 Library

types:
  SystemObjekt:
    type: object
    properties:
      id: string
      name: string
  PunktXY:
    description: Georeferenziertes SystemObjekt. Die Koordinaten werden in WGS84 abgebildet.
    type: SystemObjekt
    properties:
      breite: number
      laenge: number
  MessQuerschnitt:
    description: Ein Messquerschnitt.
    type: PunktXY
  AnzeigeQuerschnitt:
    description: Ein Anzeigequerschnitt.
    type: PunktXY
  OnlineDatum:
    type: object
    properties:
      systemObjectId: string
      datenStatus: string
      zeitstempel: datetime
  VerkehrstaerkeStunde:
    description: Anzahl der Fahrzeuge pro Stunde
    type: object
    properties:
      wert: integer
      guete: number
  Geschwindigkeit:
    description: Geschwindigkeit (von Fahrzeugen) in km/h.
    type: object
    properties:
      wert: integer
      guete: number
  VerkehrsdatenKurzzeit:
    description: Verkehrsdaten (Kurzzeit) mit Intervallwerten (normiert auf Stundenwerte).
    type: OnlineDatum
    properties:
      aspekt: string
      qKfz: VerkehrstaerkeStunde
      vKfz: Geschwindigkeit
      qLkw: VerkehrstaerkeStunde
      vLkw: Geschwindigkeit
      qPkw: VerkehrstaerkeStunde
      vPkw: Geschwindigkeit
      b:
        displayName: Belegung in Prozent
        type: number
