# This is a basic workflow to help you get started with Actions

name: Renovate-Bot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '45 8 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Self-Hosted Renovate
      # You may pin to the exact commit or the version.
      # uses: vidavidorra/github-action-renovate@8bd0ac11266c793bb7f11eafbba58167093f5de8
        uses: vidavidorra/github-action-renovate@v2.0.0
        with:
          # Configuration file to configure Renovate
          #configurationFile: # optional, default is src/config.js
          # GitHub personal access token that Renovate should use. This should be configured using a Secret.

          token: ${{ secrets.RENOVATE_TOKEN }}

      
